project:
  type: website
  output-dir: docs

# Navigation
website:
#  title: Put site title here
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: CV-10-22.pdf
        text: Curriculum vitae

# Appearance
format:
  html:
    theme: minty
    css: styles.css
    toc: true
    mainfont: sans-serif
    fontsize: 1em

# SEO Related
google_site_verification : "w9datQfVVfcFiSwl375kgWpBGTslYw1uIRqrY6zv9Bg"