project:
  type: website
  output-dir: docs

# Navigation
website:
#  title: Put site title here
  favicon: assets/favicon.png
  description: Tyler Reinmund's personal site.
  search: false
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: assets/CV-10-22.pdf
        text: Curriculum vitae

# Appearance
format:
  html:
    theme: journal
    css: styles.css
    toc: true
    link-external-newwindow: true
    citations-hover: true
    mainfont: helvetica
    fontsize: 1em
    page-layout: full
    
cookie-consent:
   type: express
   style: simple