project:
  type: website
  output-dir: docs

website:
#  title: "treinmund.github.io"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: reinmund_CV.pdf
        text: Curriculum vitae

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    mainfont: sans-serif
    fontsize: 1em