project:
  type: website
  output-dir: docs

# Navigation
website:
#  title: Put site title here
  favicon: assets/favicon.png
  description: Tyler Reinmund's personal site.
  search: false
  navbar:
    background: info
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: hai-bibliography.qmd
        text: ML in Practice

# Appearance
format:
  html:
    theme:
      - mystyles.scss
    css: styles.css
    toc: true
    link-external-newwindow: true
    citations-hover: true
    mainfont: Raleway
    fontsize: 1em
    page-layout: full

    
cookie-consent:
   type: express
   style: simple