I am a DPhil (PhD) candidate in Computer Science at the University of Oxford. I am based in the [Human-Centred Computing](https://hcc.cs.ox.ac.uk/) research group.

Additionally, I lead the [Responsible Technology Institute Student Network](https://www.rti.ox.ac.uk/student-network/), an interdisciplinary and international student-led organisation that connects graduate students who share an interest in responsible innovation.

### Research Interests

- Sociotechnical systems
- Human-automation interaction
- Applied data science
- Requirements engineering

### Education

**DPhil in Computer Science**, 2021 -- Present  
University of Oxford | Oxford, UK

**MSc in Science, Technology, & Society**, 2020 -- 2021  
University College London | London, UK

**Master of Business Administration**, 2019 -- 2020  
University of Oxford | Oxford, UK

**BS in Biomedical Engineering**, 2012 -- 2016  
Rensselaer Polytechnic Institute | Troy, US

### Acknowledgements

My academic supervisors are [Marina Jirotka](https://www.cs.ox.ac.uk/people/marina.jirotka/) and [Lars Kunze](https://ori.ox.ac.uk/people/lars-kunze/), and my studies are co-funded by Newton Europe and the Oxford-Singapore Human-Machine Collaboration Programme, supported by a gift from Amazon Web Services.